services:
  mongo:
    image: mongo:8.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - telescan_network

volumes:
  mongo_data:

networks:
  telescan_network:
    driver: bridge
